spring:
  profiles:
    active: dev
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tyw?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Hongkong
      username: root
      password: 123
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tboss?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Hongkong
      username: root
      password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  thymeleaf:
    cache: false # Enable template caching.
    check-template-location: true # Check that the templates location exists.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML5
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html
  mongodb:
    embedded:
      version: 3.6.8
      storage:
        database-dir: tboss
  redis:
    port: 6379
    host: localhost
    password: 123
    lettuce:
      pool:
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（毫秒，使用负值表示没有限制）
        max-wait: 1000
    #Redis连接超时时间单位毫秒
    timeout: 2000
# elasticsearch 配置 begin
  data:
    elasticsearch:
      cluster-name: tyw
      cluster-nodes: localhost:9300
# elasticsearch 配置 end
